"""
export.py
---------
Utilities for exporting rewritten text as TXT and PDF downloads.
"""

import io
from datetime import datetime
from typing import Optional

from fpdf import FPDF


# ---------------------------------------------------------------------------
# TXT export
# ---------------------------------------------------------------------------

def export_txt(
    original_text: str,
    rewritten_text: str,
    tone: str,
    audience: str,
) -> bytes:
    """
    Serialise the session data into a plain-text byte string for download.

    Args:
        original_text:  The user's original input.
        rewritten_text: The AI-rewritten version.
        tone:           Tone label applied during rewrite.
        audience:       Audience label applied during rewrite.

    Returns:
        UTF-8 encoded bytes ready to be used with ``st.download_button``.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        "=" * 60,
        "  ToneShift — Audience-Aware Rewriter",
        "=" * 60,
        f"  Date      : {timestamp}",
        f"  Tone      : {tone}",
        f"  Audience  : {audience}",
        "=" * 60,
        "",
        "ORIGINAL TEXT",
        "-" * 60,
        original_text,
        "",
        "REWRITTEN TEXT",
        "-" * 60,
        rewritten_text,
        "",
        "=" * 60,
        "  Generated by ToneShift (https://github.com/your-repo)",
        "=" * 60,
    ]
    return "\n".join(lines).encode("utf-8")


# ---------------------------------------------------------------------------
# PDF export
# ---------------------------------------------------------------------------

def _safe(text: str) -> str:
    """
    Encode a string to latin-1, replacing any unsupported characters,
    so fpdf2's built-in Helvetica font never raises UnicodeEncodeError.

    Args:
        text: Raw string that may contain non-latin-1 characters.

    Returns:
        A latin-1-safe string.
    """
    return text.encode("latin-1", errors="replace").decode("latin-1")


class _ToneShiftPDF(FPDF):
    """Custom FPDF subclass with header and footer."""

    def header(self) -> None:
        self.set_font("Helvetica", style="B", size=14)
        self.set_text_color(99, 102, 241)   # Indigo
        # Use ASCII hyphen instead of em-dash (latin-1 limitation)
        self.cell(0, 10, "ToneShift - Audience-Aware Rewriter", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(99, 102, 241)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self) -> None:
        self.set_y(-15)
        self.set_font("Helvetica", style="I", size=8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by ToneShift", align="C")


def export_pdf(
    original_text: str,
    rewritten_text: str,
    tone: str,
    audience: str,
    back_translation: Optional[str] = None,
    verdict: Optional[str] = None,
    confidence: Optional[int] = None,
) -> bytes:
    """
    Generate a formatted PDF containing the original, rewritten, and
    optionally the back-translation and evaluation verdict.

    Args:
        original_text:    The user's original input.
        rewritten_text:   The AI-rewritten version.
        tone:             Tone label applied during rewrite.
        audience:         Audience label applied during rewrite.
        back_translation: Optional neutral back-translation text.
        verdict:          Optional evaluation verdict string.
        confidence:       Optional confidence score (0–100).

    Returns:
        PDF file contents as bytes.
    """
    pdf = _ToneShiftPDF(orientation="P", unit="mm", format="A4")
    pdf.set_margins(left=15, top=20, right=15)
    pdf.add_page()

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # ---- Metadata block ----
    pdf.set_font("Helvetica", size=9)
    pdf.set_text_color(120, 120, 120)
    meta = _safe(f"Generated: {timestamp}   |   Tone: {tone}   |   Audience: {audience}")
    pdf.cell(0, 6, meta, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # ---- Section helper ----
    def section(title: str, body: str, color: tuple = (30, 30, 30)) -> None:
        pdf.set_font("Helvetica", style="B", size=11)
        pdf.set_text_color(99, 102, 241)
        pdf.cell(0, 8, _safe(title), new_x="LMARGIN", new_y="NEXT")
        pdf.set_draw_color(99, 102, 241)
        pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 180, pdf.get_y())
        pdf.ln(2)
        pdf.set_font("Helvetica", size=10)
        pdf.set_text_color(*color)
        pdf.multi_cell(0, 6, _safe(body))
        pdf.ln(6)

    section("Original Text", original_text)
    section("Rewritten Text", rewritten_text, color=(20, 60, 20))

    if back_translation:
        section("Back Translation (Neutral)", back_translation, color=(40, 40, 80))

    if verdict and confidence is not None:
        section(
            "Meaning Verification",
            f"Confidence: {confidence}%\nVerdict: {verdict}",
            color=(60, 30, 30) if confidence < 70 else (20, 60, 20),
        )

    # Output as bytes
    return bytes(pdf.output())
